### ISSUE TITLE
[Bug] [Sprite/Code] - Texture, Lighting, General Visual issues.

### ISSUE THREAD

**Issue by Technetium99** [HypatiaStation/HypatiaStationDev#86] opened 2015-07-17 03:32 UTC
Many tiles do not render properly or have improper coloring.
![scrnshot1](https://cloud.githubusercontent.com/assets/12611217/8740103/915248a4-2c12-11e5-8e79-d87a38034f18.png)
![untitled](https://cloud.githubusercontent.com/assets/12611217/8740105/991a39de-2c12-11e5-938e-6028f11ef62d.png)
![image](https://cloud.githubusercontent.com/assets/12611217/8740100/84a9e896-2c12-11e5-8f4f-93bfc58b6d33.png)
--> Actions
Entering the game as a character.
-->Expected result.
Normal gameplay.
-->Actual result.
See above pictures.
-->Reproducability:
Unknown at current time.
-->Severity:
GAME. BREAKING.

**Comment by Fox-McCloud** [comment] 2015-07-17 06:14
Unfixable.

duplicate of: https://github.com/HypatiaStation/HypatiaStationDev/issues/56

Short end of it; nearly all major codebases have moved over to a new lighting engine that requires hardware acceleration (Goon has had it for a while, TG got one about 6 months ago, Bay already has theirs, and then there's us, of course).

Simply put, this is because uh...your graphics card is most likely on the lower end of the spectrum.

**Closed** 2015-07-23 19:38 UTC
