### ISSUE TITLE
Graphics Problem

### ISSUE THREAD

**Issue by DrPockets** [HypatiaStation/HypatiaStationDev#68] opened 2015-07-09 22:15 UTC
Ever since the update my screen has looked like that image. If I'm ghosting and toggle darkness then everything looks normal again.
![image](https://cloud.githubusercontent.com/assets/13263256/8608174/771c8c4e-2666-11e5-8e88-6c3c3c1e7410.png)

**Comment by TwistedAkai** [comment] 2015-07-09 23:25
That looks like lighting alphas aren't working for you. Logging in, I don't see that at all, suggesting it's specific to you. What BYOND version are you using?

**Comment by TwistedAkai** [comment] 2015-07-09 23:35
Duplicate of #56

**Comment by DrPockets** [comment] 2015-07-10 00:45
My Byond is up to date. Very odd because it happened the moment the update dropped.

**Comment by Rohaneanew** [comment] 2015-07-10 00:47
See go check the referenced and try those instructions, then report back and see if it works.

**Comment by DrPockets** [comment] 2015-07-10 00:54
I turned off the option to use graphics hardware for displaying maps and still it displays the bug. It only goes away if I toggle darkness.

**Comment by Fox-McCloud** [comment] 2015-07-10 01:31
YOu want graphics acceleration turned *ON* not off.

If your BYOND is up to date, your graphics driver are up to date, and your graphics acceleration are all turned on and you're still suffering form this issues, there's really not much that can be done--you won't be able to play until you get a graphics card that does support hardware acceleration.

**Closed** 2015-08-13 20:06 UTC
Labels: duplicate
