### ISSUE TITLE
[Low][Bug]Ore Redemption Machine

### ISSUE THREAD

**Issue by Ltmayday** [HypatiaStation/HypatiaStationDev#30] opened 2015-07-06 01:41 UTC
**Description of the Bug**:Ore Machine wont work at all
**What were you doing when the bug happened**:i tryed to test the Ore Redemption Machine with a Ore Box, but did not work...so i tryed it by emptying the ore box and see if the ore loads, tryed it on the other side to
**What was the expected result of your actions**:no result at all, did not even instantly transform the ore in to it into workable material sheets
**What actually happened**:sod all happened..
**Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**:tested it 4 timesish
**Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**:Low to Medium

**Comment by Fox-McCloud** [comment] 2015-07-06 07:33
this probably need some landmark effects set for input and output--could be wrong; the ore redemption machine isn't really ready for prime time as mining hasn't been updated yet.

**Comment by Rohaneanew** [comment] 2015-07-06 08:43
This is a duplicate of #27. This will be placed on low priority and will become functional when we get the code from downstream.

**Comment by Fox-McCloud** [comment] 2015-07-06 08:57
@Rohaneanew 

I do think there's landmark effects that can be placed ont he map to make this functional--but I could be wrong...I haven't poked at the code much because I know it's going to get changed eventually.

**Comment by CrowOfBourbon** [comment] 2015-07-06 15:56
I may have just fixed all of this. The map was using machines that didn't have some sort of icon (idk, ORIGINAL MINING MACHINES MAPPED)

I won't close this till we see if I fixed it.

**Comment by Ltmayday** [comment] 2015-07-07 11:35
mining outpost fixed..and working nicely.

**Comment by CrowOfBourbon** [comment] 2015-07-08 01:45
PEACHY! Closing this.

**Closed by CrowOfBourbon** 2015-07-08 01:45 UTC
Labels: duplicate
