### ISSUE TITLE
[Medium][Bug][Map] Telescience console not linked to telepad

### ISSUE THREAD

**Issue by Grolarg** [HypatiaStation/HypatiaStationDev#36] opened 2015-07-06 16:06 UTC
**Description of the Bug**: The telescience control console seems to not be linked to the telepad in the lab. When using the console, it asks me to add telepad info, but there seems to be no way to do so in game.
    **What were you doing when the bug happened**: Trying to use the Telescience lab.
    **What was the expected result of your actions**: Using the Teleporter console to activate the telepad
    **What actually happened**: An error telling me the console isn't linked to the pad
    **Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself**: Every time the console is used
    **Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]**: At least Medium, as it makes that entire lab unusable.

**Comment by CrowOfBourbon** [comment] 2015-07-06 19:34
How the Bloody fuck do I fix this.... I'll check in to it.

I swear, if it's another ID tag thing, I'mma kick a cat.

**Comment by Fox-McCloud** [comment] 2015-07-06 21:05
Not a bug. 

The telesci pad must be manually linked to the console.

Open the pad with a screwdriver, save its information to the buffer in a multitool, close the telesci pad, then load the buffered info (in the multiool) into the telesci console by clicking the multitool on the console.

**Comment by CrowOfBourbon** [comment] 2015-07-06 22:22
Closing this then. Thanks! <3

**Closed by CrowOfBourbon** 2015-07-06 22:22 UTC
